POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
  "body": "This is a valid chirp!"
}

###
POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
  "body": "This is an invalid chirp because it is way too long................................................................................................."
}

###
POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
  "body": "I dislike the kerfuffle and the sharbert situation"
}

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "email": "user5@example.com"
}

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "saul@bettercall.com"
}

###
POST http://localhost:8080/api/chirps
Content-Type: application/json

{
  "body": "This is my first chirp!",
  "user_id": "550e8400-e29b-41d4-a716-446655440000"
}

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "lane@example.com",
  "password": "04234"
}

###
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email": "lane@example.com",
  "password": "04234"
}

###
POST http://localhost:8080/admin/reset
Content-Type: application/json
